branches/prototype-beta/pydjango/apps/oi/urls.py
from django.core import urlresolvers
from django.conf.urls.defaults import *
from django.conf import settings

from apps.oi import views as oi_views

urlpatterns = patterns('',
    # Publisher URLs
    url(r'^publisher/(?P<id>\d+)/reserve/$', oi_views.reserve,
        { 'model_name': 'publisher' }, name='reserve_publisher'),
    url(r'^publisher/(?P<id>\d+)/edit/$', oi_views.direct_edit,
        { 'model_name': 'publisher' }, name='direct_edit_publisher'),
    url(r'^publisher/revision/(?P<id>\d+)/submit/$', oi_views.submit,
        { 'model_name': 'publisher' }, name='submit_publisher'),
    url(r'^publisher/revision/(?P<id>\d+)/process/$', oi_views.process,
        { 'model_name': 'publisher' }, name='process_publisher'),
    url(r'^publisher/revision/(?P<id>\d+)/edit/$', oi_views.edit,
        { 'model_name': 'publisher' }, name='edit_publisher'),
    url(r'^publisher/revision/(?P<id>\d+)/discard/$', oi_views.discard,
        { 'model_name': 'publisher' }, name='discard_publisher'),
    url(r'^publisher/revision/(?P<id>\d+)/examine/$', oi_views.examine,
        { 'model_name': 'publisher' }, name='examine_publisher'),
    url(r'^publisher/revision/(?P<id>\d+)/release/$', oi_views.release,
        { 'model_name': 'publisher' }, name='release_publisher'),
    url(r'^publisher/revision/(?P<id>\d+)/approve/$', oi_views.approve,
        { 'model_name': 'publisher' }, name='approve_publisher'),
    url(r'^publisher/revision/(?P<id>\d+)/disapprove/$', oi_views.disapprove,
        { 'model_name': 'publisher' }, name='disapprove_publisher'),

    # Series URLs
    url(r'^series/(?P<id>\d+)/reserve/$', oi_views.reserve,
        { 'model_name': 'series' }, name='reserve_series'),
    url(r'^series/(?P<id>\d+)/edit/$', oi_views.direct_edit,
        { 'model_name': 'series' }, name='direct_edit_series'),
    url(r'^series/revision/(?P<id>\d+)/submit/$', oi_views.submit,
        { 'model_name': 'series' }, name='submit_series'),
    url(r'^series/revision/(?P<id>\d+)/process/$', oi_views.process,
        { 'model_name': 'series' }, name='process_series'),
    url(r'^series/revision/(?P<id>\d+)/edit/$', oi_views.edit,
        { 'model_name': 'series' }, name='edit_series'),
    url(r'^series/revision/(?P<id>\d+)/discard/$', oi_views.discard,
        { 'model_name': 'series' }, name='discard_series'),
    url(r'^series/revision/(?P<id>\d+)/examine/$', oi_views.examine,
        { 'model_name': 'series' }, name='examine_series'),
    url(r'^series/revision/(?P<id>\d+)/release/$', oi_views.release,
        { 'model_name': 'series' }, name='release_series'),
    url(r'^series/revision/(?P<id>\d+)/approve/$', oi_views.approve,
        { 'model_name': 'series' }, name='approve_series'),
    url(r'^series/revision/(?P<id>\d+)/disapprove/$', oi_views.disapprove,
        { 'model_name': 'series' }, name='disapprove_series'),

    url(r'^queues/reserved/$', oi_views.show_reserved),
    url(r'^queues/pending/$', oi_views.show_pending),
    url(r'^queues/reviews/$', oi_views.show_reviews),
)

branches/prototype-beta/pydjango/apps/gcd/models/indexcredit.py
from django.db import models

from indexer import Indexer
from series import Series

class IndexCredit(models.Model):
    """ indexing credits from gcd database"""

    class Meta:
        db_table = 'IndexCredit'
        app_label = 'gcd'

    class Admin:
        pass

    id = models.AutoField(primary_key = True, db_column = 'ID')

    indexer = models.ForeignKey(Indexer, db_column = 'IndexerID',
                                related_name = 'index_credit_set')
    series = models.ForeignKey(Series, db_column = 'SeriesID',
                               related_name = 'index_credit_set')
    run = models.CharField(max_length = 255, db_column = 'Run', null = True)
    notes = models.TextField(db_column = 'Notes', null = True)
    comment = models.TextField(db_column = 'Comment', null = True)

    modified = models.DateField(db_column = 'DateMod',
                                auto_now = True, null = True)

branches/prototype-beta/pydjango/apps/gcd/models/issue.py
from django.db import models

from series import Series

class Issue(models.Model):
    """ issue from gcd database"""

    class Meta:
        db_table = 'issues'
        app_label = 'gcd'
        ordering = ['key_date']

    class Admin:
        pass

    id = models.AutoField(primary_key = True, db_column = 'ID')

    # Core issue attributes.
    # Note that volume is not consistently used at this time, and
    # is usually included in 'issue' when it is of critical importance.
    volume = models.IntegerField(max_length = 255, db_column = 'VolumeNum',
                                 null = True)
    number = models.CharField(max_length = 25, db_column = 'Issue',
                              null = True)
    # Note that in stories, publication_date is limited to 50 chars.
    publication_date = models.CharField(max_length = 255,
                                        db_column = 'Pub_Date',
                                        null = True)
    price = models.CharField(max_length = 25, db_column = 'Price', null = True)
    story_count = models.IntegerField(db_column = 'storycount', null = True)
    key_date = models.CharField(max_length = 10, db_column = 'Key_Date',
                                null = True)

    # Fields related to indexing activities.
    # Only "reserved" is in active use, the others are legacy fields
    # used only by migration scripts.
    reserved = models.BooleanField(default=0)
    index_status = models.IntegerField(db_column = 'IndexStatus', null = True)
    reserve_status = models.IntegerField(db_column = 'ReserveStatus',
                                         null = True)

    # Attributes from series table. First is foreign key, rest are
    # dups and seem to be ignored in the lasso implementation
    series = models.ForeignKey(Series,
                               db_column = 'SeriesID')

    # Fields related to change management.
    created = models.DateTimeField(auto_now_add = True, null = True)
    modified = models.DateTimeField(db_column = 'Modified',
                                    auto_now = True, null = True)
    
    def index_status_description(self):
        """Text form of status.  If clauses arranged in order of most
        likely case to least."""
        if (self.index_status == 3):
            return 'approved'
        if (self.index_status == 0):
            return 'no data'
        if (self.index_status == 1):
            return 'reserved'
        if (self.index_status == 2):
            return 'pending'

    def reserver(self):
        """
        Return the likely current reservation holder.  While it is common
        for an issue to have multiple reservation records for the same issue
        in the same status, at no point in the current (at this time) data set
        does an issue have more than one unapproved reservation record with
        differen indexers in each.  So taking the first 
        """
        if self.index_status in (1, 2):
            reservers = self.reservation_set.filter(status=self.index_status)
            if reservers.count() > 0:
                return reservers[0].indexer
        return None

    def get_absolute_url(self):
        return "/issue/%i/" % self.id

    def __unicode__(self):
        return u'%s #%s' % (self.series, self.number)

branches/prototype-beta/pydjango/apps/gcd/models/reservation.py
from django.db import models

from indexer import Indexer
from issue import Issue

class Reservation(models.Model):
    """
    Issue-level reservations in the OI.
    """

    class Meta:
        db_table = 'Reservations'
        app_label = 'gcd'

    class Admin:
        pass

    id = models.AutoField(primary_key=True, db_column='ID')

    indexer = models.ForeignKey(Indexer, db_column='IndexerID',
                                related_name='reservation_set')
    issue = models.ForeignKey(Issue, db_column='IssueID',
                               related_name='reservation_set')
    status = models.IntegerField(null=True, blank=True, db_column='Status')

    # NOTE: there are two rows with a non-null but 0000-00-00 date
    # which will need to be fixed or else python date objects won't work.
    expires = models.DateField(null=True, blank=True, db_column='Expires')

    created = models.DateField(auto_now=True, null=True, editable=False,
                               db_column='Created')

    # NOTE: this appears to always be 1.
    index_type = models.IntegerField(null=True, blank=True,
                                     db_column='IndexType')

branches/prototype-beta/pydjango/templates/gcd/details/publisher.html
{% extends "gcd/base_view.html" %}

{% load i18n %}

{% block title %}
  {% if publisher.is_imprint %}
    GCD :: Publisher :: {{ publisher.parent.name }} :: Imprint :: {{ publisher.name }}
  {% else %}
    GCD :: Publisher :: {{ publisher.name }}
  {% endif %}
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css"
      href="{{ MEDIA_URL }}/css/gcd/{{ style }}.css"/>
{% endblock %}

{% block view_body %}

{% include "gcd/bits/publisher_header.html" %}

{% comment %}
{% if publisher.reserved %}
  {% with publisher.revisions.all.0 as revision %}
    <div id="index_status" class="index_status_{{ revision.state }}">
    <span>
    {% ifequal revision.state 1 %}
       This {% if publisher.is_imprint %}imprint{% else %}publisher{% endif %}
        is currently being edited by
       {{ revision.indexer.indexer|default:"[no one, please contact the editors to fix this reservation]" }}
       (since {{ revision.created }}, last edit {{ revision.modified }})
    {% endifequal %}
    {% ifequal revision.state 2 %}
       Edits to this
       {% if publisher.is_imprint %}imprint{% else %}publisher{% endif %}
        are currently awaiting approval.
    {% endifequal %}
    </span>
    </div>
  {% endwith %}
{% else %}
  <div id="control_panel">
  <form method="POST"
        action="{% url reserve_publisher id=publisher.id %}">
    <input id="edit" name="edit" type="submit" value="Edit" />
  </form>
  </div>
{% endif %}
{% endcomment %}

<div>
  <dl class="pub_data">
  {% if publisher.country %}
    <dt> Country:
    <dd> {{ publisher.country.name }}
  {% endif %}

  {% if publisher.has_imprints %}
    <dt> Imprints:
    <dd> <a href="{{ publisher.get_absolute_url }}imprints/">{{ publisher.imprint_set.count }}</a>
  {% endif %}

  {% if publisher.notes %}
    <dt> Notes:
    <dd> {{ publisher.notes|linebreaksbr }}
  {% endif %}

  {% if publisher.url %}
    <dt> Web Site:
    <dd> <a href="{{ publisher.get_official_url }}">{{ publisher.url }}</a>
  {% endif %}

{% ifequal page.object_list.count 0 %}
    <dt> Titles:
    <dd> None
  </dl>
</div>
{% else %}
  </dl>
</div>

<table id="publisher_detail_listing" class="listing">
  <tr>
    <th> Title </th>
    <th> Year </th>
    <th> #&nbsp;Issues </th>
    <th> Covers </th>
    <th> Published </th>
  </tr>
  {% for series in page.object_list %}
  <tr class="{% cycle 'listing_even' 'listing_odd' %}">
    <td> <a href="{{ series.get_absolute_url }}">{{ series.name }}</a> </td>
    <td> {{ series.year_began }}
    <td> {{ series.issue_set.count }} issue{{ series.issue_count|pluralize }} </td>
    {% if not series.scan_needed %}
    <td> <a href="{% url apps.gcd.views.details.covers series_id=series.id %}">Gallery</a>
    {% else %}
      {% if series.has_gallery %}
        <td> <a href="{% url apps.gcd.views.details.covers series_id=series.id %}">Have 
        {{ series.scan_count}}</a>
        (<a href="{% url apps.gcd.views.details.scans series_id=series.id %}">Need 
        {{ series.scan_needed }}</a>)
      {% else %}
        <td> <a href="{% url apps.gcd.views.details.scans series_id=series.id %}">Add</a>
      {% endif %}
    {% endif %}
    <td> {{ series.publication_dates }} </td>
  </tr>
  {% endfor %}
</table>
{% endifequal %}

{% with 1 as paginate_only %}
{% include "gcd/bits/publisher_header.html" %}
{% endwith %}

{% endblock %}